name: meu CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo Incializando Build...
          echo Branch utilizada ${{ github.ref_name }}, Evento ${{ github.event_name }}.
